name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: '5.4.7'

      - name: Install busted
        run: luarocks install busted

      - name: Run Lua tests
        working-directory: ./Modules
        run: busted Helpers.test.lua